# Generated by Django 4.0 on 2021-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=50, null=True)),
                ('categorydescription', models.CharField(blank=True, db_column='categoryDescription', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.CharField(db_column='studentID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
