# Generated by Django 4.0 on 2021-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_categories_students_delete_djangosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('countyname', models.CharField(db_column='countyName', max_length=30, primary_key=True, serialize=False)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('patientid', models.CharField(db_column='patientID', max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('facultyid', models.CharField(db_column='facultyID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'professors',
                'managed': False,
            },
        ),
    ]
