# Generated by Django 4.0 on 2021-12-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_counties_covid_professors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
        migrations.DeleteModel(
            name='Covid',
        ),
        migrations.DeleteModel(
            name='Professors',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
